### PR TITLE
Value changes

### PR DESCRIPTION
**Pull request by NSoiffer**
Lots of updates. See details with each commit.

### CODE REVIEW

**Review by davidcarlisle — APPROVED** [review]

**Review by davidcarlisle — APPROVED** [review]
on 22ba see also https://tex.stackexchange.com/a/435363/1090

**Review by davidcarlisle — APPROVED** [review]

**Review by davidcarlisle — APPROVED** [review]

**Comment by davidcarlisle** [comment]
Merged there were four conflicts I took your branch in each case but you might want to check


```
<description>MULTIPLE CHARACTER OPERATOR: //</description>
<description unicode="combination">LEFT TRIANGLE BESIDE VERTICAL BAR with slash</description>
<description unicode="3.2">VERTICAL BAR BESIDE RIGHT TRIANGLE</description>
<description unicode="combination">VERTICAL BAR BESIDE RIGHT TRIANGLE with slash</description>
```

**Comment by NSoiffer** [comment]
Thanks. I did a pull before making the changes, but clearly I'm not doing
it correctly.

In regards to those changes, github won't show me "blame" because the file
is too big. Do you know what the values were that caused the conflict? I
have a lot of comments about why I did what I did, but not for those
characters. Off the top of my head, it looks like they should have
priority="240". Was that their old value? I looked at your "resolve" diff
and didn't see the change there for some reason.

    Neil

**Comment by davidcarlisle** [comment]
I could recreate the diff I think, give me a minute,, I think one was different priority values and the others were adding or removing an operator dictionary entry, and one was a dropped unicode `<description` element that I restored.

**Pull request merged**
